<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="2" total="10" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="SuiteWithGroups" duration-ms="248" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
    <groups>
    </groups>
    <test name="testWorkWithGroups" duration-ms="248" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
      <class name="edu.pht.collections.entity.PageMethodsWithExceptionTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeSuite" is-config="true" duration-ms="40" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeTest" is-config="true" duration-ms="1" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeClass" is-config="true" duration-ms="23" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="60" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test_GetElementsDropdown_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_GetElementsDropdown_Exception" duration-ms="10" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <exception class="edu.pht.collections.exception.NoSuchEntityException">
            <message>
              <![CDATA[ NoSuchEntityException ->  LogicException -> the saved third can not be found for set -> to store the order of the elements use list]]>
            </message>
            <full-stacktrace>
              <![CDATA[ NoSuchEntityException [resume=to store the order of the elements use list, getDetail()=the saved third can not be found for set]
at edu.pht.collections.entity.Page.getElementsDropdown(Page.java:115)
at edu.pht.collections.entity.PageMethodsWithExceptionTest.test_GetElementsDropdown_Exception(PageMethodsWithExceptionTest.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- edu.pht.collections.exception.NoSuchEntityException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_GetElementsDropdown_Exception -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test_GetElementsDropdown_Message_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_GetElementsDropdown_Message_Exception" duration-ms="7" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_GetElementsDropdown_Message_Exception -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="5" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test_GetFirstField_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_GetFirstField_Exception" duration-ms="2" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <exception class="edu.pht.collections.exception.NoSuchEntityException">
            <message>
              <![CDATA[ NoSuchEntityException ->  LogicException -> field element not found -> list of fields is empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[ NoSuchEntityException [resume=list of fields is empty, getDetail()=field element not found]
at edu.pht.collections.entity.Page.getFirstField(Page.java:83)
at edu.pht.collections.entity.PageMethodsWithExceptionTest.test_GetFirstField_Exception(PageMethodsWithExceptionTest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- edu.pht.collections.exception.NoSuchEntityException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_GetFirstField_Exception -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test_GetFirstField_Message_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_GetFirstField_Message_Exception" duration-ms="2" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_GetFirstField_Message_Exception -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="test_GetLastField_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_GetLastField_Exception" duration-ms="2" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <exception class="edu.pht.collections.exception.NoSuchEntityException">
            <message>
              <![CDATA[ NoSuchEntityException ->  LogicException -> field element not found -> list of fields is empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[ NoSuchEntityException [resume=list of fields is empty, getDetail()=field element not found]
at edu.pht.collections.entity.Page.getLastField(Page.java:90)
at edu.pht.collections.entity.PageMethodsWithExceptionTest.test_GetLastField_Exception(PageMethodsWithExceptionTest.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- edu.pht.collections.exception.NoSuchEntityException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_GetLastField_Exception -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="2" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test_GetLastField_Message_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_GetLastField_Message_Exception" duration-ms="6" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_GetLastField_Message_Exception -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test_In_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_In_Exception" duration-ms="30" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <exception class="edu.pht.collections.exception.InvalidActionException">
            <message>
              <![CDATA[ InvalidActionException ->  LogicException -> collection element must extends class Dropdown -> this is a unvailable action]]>
            </message>
            <full-stacktrace>
              <![CDATA[ InvalidActionException [resume=this is a unvailable action, getDetail()=collection element must extends class Dropdown]
at edu.pht.collections.entity.Page.in(Page.java:102)
at edu.pht.collections.entity.PageMethodsWithExceptionTest.test_In_Exception(PageMethodsWithExceptionTest.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- edu.pht.collections.exception.InvalidActionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_In_Exception -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="test_In_Message_Exception()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="test_In_Message_Exception" duration-ms="1" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_In_Message_Exception -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterMethod" is-config="true" duration-ms="2" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterClass" is-config="true" duration-ms="1" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-08-14T01:04:06Z" finished-at="2018-08-14T01:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:edu.pht.collections.entity.PageMethodsWithExceptionTest@4678c730]" name="afterSuite" is-config="true" duration-ms="1" started-at="2018-08-14T01:04:07Z" finished-at="2018-08-14T01:04:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- edu.pht.collections.entity.PageMethodsWithExceptionTest -->
    </test> <!-- testWorkWithGroups -->
  </suite> <!-- SuiteWithGroups -->
</testng-results>
